/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as AuthLayoutImport } from './routes/auth/layout'
import { Route as LayoutImport } from './routes/layout'
import { Route as StoriesIndexImport } from './routes/stories/index'
import { Route as MessagesIndexImport } from './routes/messages/index'
import { Route as GroupsIndexImport } from './routes/groups/index'
import { Route as AnalyticsIndexImport } from './routes/analytics/index'
import { Route as AuthRegisterIndexImport } from './routes/auth/register/index'
import { Route as AuthLogoutIndexImport } from './routes/auth/logout/index'
import { Route as AuthLoginIndexImport } from './routes/auth/login/index'

// Create/Update Routes

const AuthLayoutRoute = AuthLayoutImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRoute,
} as any)

const LayoutRoute = LayoutImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const StoriesIndexRoute = StoriesIndexImport.update({
  id: '/stories/',
  path: '/stories/',
  getParentRoute: () => rootRoute,
} as any)

const MessagesIndexRoute = MessagesIndexImport.update({
  id: '/messages/',
  path: '/messages/',
  getParentRoute: () => rootRoute,
} as any)

const GroupsIndexRoute = GroupsIndexImport.update({
  id: '/groups/',
  path: '/groups/',
  getParentRoute: () => rootRoute,
} as any)

const AnalyticsIndexRoute = AnalyticsIndexImport.update({
  id: '/analytics/',
  path: '/analytics/',
  getParentRoute: () => rootRoute,
} as any)

const AuthRegisterIndexRoute = AuthRegisterIndexImport.update({
  id: '/register/',
  path: '/register/',
  getParentRoute: () => AuthLayoutRoute,
} as any)

const AuthLogoutIndexRoute = AuthLogoutIndexImport.update({
  id: '/logout/',
  path: '/logout/',
  getParentRoute: () => AuthLayoutRoute,
} as any)

const AuthLoginIndexRoute = AuthLoginIndexImport.update({
  id: '/login/',
  path: '/login/',
  getParentRoute: () => AuthLayoutRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof LayoutImport
      parentRoute: typeof rootRoute
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthLayoutImport
      parentRoute: typeof rootRoute
    }
    '/analytics/': {
      id: '/analytics/'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AnalyticsIndexImport
      parentRoute: typeof rootRoute
    }
    '/groups/': {
      id: '/groups/'
      path: '/groups'
      fullPath: '/groups'
      preLoaderRoute: typeof GroupsIndexImport
      parentRoute: typeof rootRoute
    }
    '/messages/': {
      id: '/messages/'
      path: '/messages'
      fullPath: '/messages'
      preLoaderRoute: typeof MessagesIndexImport
      parentRoute: typeof rootRoute
    }
    '/stories/': {
      id: '/stories/'
      path: '/stories'
      fullPath: '/stories'
      preLoaderRoute: typeof StoriesIndexImport
      parentRoute: typeof rootRoute
    }
    '/auth/login/': {
      id: '/auth/login/'
      path: '/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginIndexImport
      parentRoute: typeof AuthLayoutImport
    }
    '/auth/logout/': {
      id: '/auth/logout/'
      path: '/logout'
      fullPath: '/auth/logout'
      preLoaderRoute: typeof AuthLogoutIndexImport
      parentRoute: typeof AuthLayoutImport
    }
    '/auth/register/': {
      id: '/auth/register/'
      path: '/register'
      fullPath: '/auth/register'
      preLoaderRoute: typeof AuthRegisterIndexImport
      parentRoute: typeof AuthLayoutImport
    }
  }
}

// Create and export the route tree

interface AuthLayoutRouteChildren {
  AuthLoginIndexRoute: typeof AuthLoginIndexRoute
  AuthLogoutIndexRoute: typeof AuthLogoutIndexRoute
  AuthRegisterIndexRoute: typeof AuthRegisterIndexRoute
}

const AuthLayoutRouteChildren: AuthLayoutRouteChildren = {
  AuthLoginIndexRoute: AuthLoginIndexRoute,
  AuthLogoutIndexRoute: AuthLogoutIndexRoute,
  AuthRegisterIndexRoute: AuthRegisterIndexRoute,
}

const AuthLayoutRouteWithChildren = AuthLayoutRoute._addFileChildren(
  AuthLayoutRouteChildren,
)

export interface FileRoutesByFullPath {
  '/': typeof LayoutRoute
  '/auth': typeof AuthLayoutRouteWithChildren
  '/analytics': typeof AnalyticsIndexRoute
  '/groups': typeof GroupsIndexRoute
  '/messages': typeof MessagesIndexRoute
  '/stories': typeof StoriesIndexRoute
  '/auth/login': typeof AuthLoginIndexRoute
  '/auth/logout': typeof AuthLogoutIndexRoute
  '/auth/register': typeof AuthRegisterIndexRoute
}

export interface FileRoutesByTo {
  '/': typeof LayoutRoute
  '/auth': typeof AuthLayoutRouteWithChildren
  '/analytics': typeof AnalyticsIndexRoute
  '/groups': typeof GroupsIndexRoute
  '/messages': typeof MessagesIndexRoute
  '/stories': typeof StoriesIndexRoute
  '/auth/login': typeof AuthLoginIndexRoute
  '/auth/logout': typeof AuthLogoutIndexRoute
  '/auth/register': typeof AuthRegisterIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof LayoutRoute
  '/auth': typeof AuthLayoutRouteWithChildren
  '/analytics/': typeof AnalyticsIndexRoute
  '/groups/': typeof GroupsIndexRoute
  '/messages/': typeof MessagesIndexRoute
  '/stories/': typeof StoriesIndexRoute
  '/auth/login/': typeof AuthLoginIndexRoute
  '/auth/logout/': typeof AuthLogoutIndexRoute
  '/auth/register/': typeof AuthRegisterIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/analytics'
    | '/groups'
    | '/messages'
    | '/stories'
    | '/auth/login'
    | '/auth/logout'
    | '/auth/register'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/analytics'
    | '/groups'
    | '/messages'
    | '/stories'
    | '/auth/login'
    | '/auth/logout'
    | '/auth/register'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/analytics/'
    | '/groups/'
    | '/messages/'
    | '/stories/'
    | '/auth/login/'
    | '/auth/logout/'
    | '/auth/register/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  LayoutRoute: typeof LayoutRoute
  AuthLayoutRoute: typeof AuthLayoutRouteWithChildren
  AnalyticsIndexRoute: typeof AnalyticsIndexRoute
  GroupsIndexRoute: typeof GroupsIndexRoute
  MessagesIndexRoute: typeof MessagesIndexRoute
  StoriesIndexRoute: typeof StoriesIndexRoute
}

const rootRouteChildren: RootRouteChildren = {
  LayoutRoute: LayoutRoute,
  AuthLayoutRoute: AuthLayoutRouteWithChildren,
  AnalyticsIndexRoute: AnalyticsIndexRoute,
  GroupsIndexRoute: GroupsIndexRoute,
  MessagesIndexRoute: MessagesIndexRoute,
  StoriesIndexRoute: StoriesIndexRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/auth",
        "/analytics/",
        "/groups/",
        "/messages/",
        "/stories/"
      ]
    },
    "/": {
      "filePath": "layout.tsx"
    },
    "/auth": {
      "filePath": "auth/layout.tsx",
      "children": [
        "/auth/login/",
        "/auth/logout/",
        "/auth/register/"
      ]
    },
    "/analytics/": {
      "filePath": "analytics/index.tsx"
    },
    "/groups/": {
      "filePath": "groups/index.tsx"
    },
    "/messages/": {
      "filePath": "messages/index.tsx"
    },
    "/stories/": {
      "filePath": "stories/index.tsx"
    },
    "/auth/login/": {
      "filePath": "auth/login/index.tsx",
      "parent": "/auth"
    },
    "/auth/logout/": {
      "filePath": "auth/logout/index.tsx",
      "parent": "/auth"
    },
    "/auth/register/": {
      "filePath": "auth/register/index.tsx",
      "parent": "/auth"
    }
  }
}
ROUTE_MANIFEST_END */
