import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { AuthProvider } from "@/lib/providers/auth-provider";
import { QueryClientProvider } from "@tanstack/react-query";
import QueryProvider from "@/lib/providers/tanstackquery-provider";
import { Suspense } from "react";
import { LoaderPinwheel } from "lucide-react";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: {
    template: "%s | SlowChat",
    default: "SlowChat App",
  },
  description: "Generated by Ibrahim Zaman (abrahimzaman360)",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        suppressHydrationWarning
        suppressContentEditableWarning
      >
        <QueryProvider>
          <Suspense
            fallback={
              <div className="flex flex-col items-center justify-center h-screen">
                <LoaderPinwheel className="animate-spin" />
              </div>
            }
          >
            <AuthProvider>{children}</AuthProvider>
            {/* <NetworkConnectivity /> */}
            {/* <MoveTop /> */}
          </Suspense>
          {/* <ReactQueryDevtools initialIsOpen={false} /> */}
        </QueryProvider>
      </body>
    </html>
  );
}
