import type { Metadata } from "next";
import { SidebarInset, SidebarProvider } from "@/components/ui/sidebar";
import { AppSidebar } from "@/components/app/shared/sidebar/app-sidebar";
export const metadata: Metadata = {
  title: "Home",
  description: "Generated by Ibrahim Zaman (abrahimzaman360)",
};

export default function AppLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <SidebarProvider>
      <AppSidebar variant="floating" />
      <SidebarInset>
        <div className="rounded-md">
          {children}
        </div>
      </SidebarInset>
    </SidebarProvider>
  );
}
